package commons

import (
	"fmt"
	"testing"
	"time"
)

func TestTime(t *testing.T) {
	tt := Now()
	fmt.Println("Hour: ", tt.Hour())
	tt = tt.In(time.UTC)
	fmt.Println("Hour: ", tt.Hour())
	tz := time.FixedZone("Asia/Seoul", 9*60*60)
	tt = time.Now().In(tz)
	fmt.Println("Timezone: ", tz)
	fmt.Println("commons utc Hour: ", tt.Hour())
	fmt.Println("Today: ", Today())
	tm := GetTimestamp("2006-01-02", "2019-05-05")
	fmt.Println("Childrens Day: ", tm)

	// Test if timestamp generated by commons is consistent
	now := Now()
	nowTimestamp := now.Unix()
	nowAgain := Unix(nowTimestamp)
	nowAgainTimestamp := nowAgain.Unix()
	fmt.Printf("Now: %d Again: %d\n", nowTimestamp, nowAgainTimestamp)
	fmt.Println("Is Equal: ", nowTimestamp == nowAgainTimestamp)
}
